name: Deploy JSON Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - name: Install Dependencies
        run: npm install

      - name: Start JSON Server
        run: npm start

      - name: Send Notification Email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.projetoconfeitaria8@gmail.com }}
          password: ${{ secrets.qwerty567@ }}
          subject: Deploy Status
          body: The deploy was ${{ job.status }}.
          to: projetoconfeitaria8@gmail.com
          from: GitHub Actions
