name: Deploy JSON Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Start JSON Server
        run: |
        npm install --prefix src
        npm run start-json-server --prefix src
    env:
    PORT: ${{ secrets.PORT }}
    DATABASE_URL: ${{ secrets.DATABASE_URL }}
    EMAIL: ${{ secrets.EMAIL }}
    PASSWORD: ${{ secrets.PASSWORD }}
